### ISSUE TITLE
Error in function isDarkModeEnabled()

### ISSUE THREAD

**Issue by package71** [EddyVerbruggen/nativescript-dark-mode#1]
iPhone 6s (iOS: 13) 

Example code:
```

    let isDarkMode = false;
   
    if (isDarkModeSupported()) {
      isDarkMode = isDarkModeEnabled();
    }
```
Error stack
```

*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'frame_1.topmost().viewController')
at
isDarkModeEnabled(file:///node_modules/nativescript-dark-mode/dark-mode.js:25:29)
at data(file:///app/pages/main/main.vue:53:0)
at getData(file:///node_modules/nativescript-vue/dist/index.js:4485:21)
at initData(file:///node_modules/nativescript-vue/dist/index.js:4442:14)
at initState(file:///node_modules/nativescript-vue/dist/index.js:4379:13)
at _init(file:///node_modules/nativescript-vue/dist/index.js:4813:14)
at VueComponent(file:///node_modules/nativescript-vue/dist/index.js:13603:17)
at createComponentInstanceForVnode(file:///node_modules/nativescript-vue/dist/index.js:5678:41)
at init(file:///node_modules/nativescript-vue/dist/index.js:5510:8)
at createComponent(file:///node_modules/nativescript-vue/dist/index.js:6823:10)
at createElm(file:///node_modules/nativescript-vue/dist/index.js:6770:24)
at createChildren(file:///node_modules/nativescript-vue/dist/index.js:6898:18)
at createElm(file:///node_modules/nativescript-vue/dist/index.js:6799:23)
at patch(file:///node_modules/nativescript-vue/dist/index.js:7322:16)

```

**Comment by Sartxi** [comment]
I am seeing the same problem:

`JavaScript error: file:///node_modules/nativescript-dark-mode/dark-mode.js:25:0: JS ERROR TypeError: undefined is not an object (evaluating 'frame_1.topmost().viewController')`

**Comment by niksudan** [comment]
This was occurring for me due to working with a frame that wasn't loaded yet. If you are using Angular, make use to check this in the `ngAfterViewInit` lifecycle method.

From the NativeScript docs:

> We can get a reference to a Frame only for a frame that has been already loaded in the visual tree. Frames that are not still loaded (for example a Frame within a modal page that is not yet opened) can not be retrieved.

https://docs.nativescript.org/ui/components/frame#frame-reference

**Comment by bkwhite** [comment]
I seem to get this error using NativeScript-Vue in any component I try to call it in.

**Comment by YanVetrov** [comment]
> I seem to get this error using NativeScript-Vue in any component I try to call it in.


If anyone use NS-Vue, you can use babel-dymanic-imports in @loaded handler method on top frame for example:
`<Frame @loaded="frameLoaded">
      <slot name="mainContent" />
    </Frame>`

`  methods: {
    frameLoaded() {
      import("nativescript-dark-mode").then(plugin => {
        Vue.prototype.$darkMode = {
          on: plugin.addOnDarkModeChangedListener,
          isEnabled: plugin.isDarkModeEnabled,
          isSupported: plugin.isDarkModeSupported
      });
    }
  }`

**Comment by package71** [comment]
I've found bug and solve it 
This plugin used deprecated method

> Module UserInterfaceStyle
> deprecated
> use SystemAppearance instead.
> 
> Specifies the types of the user interface style.
> https://docs.nativescript.org/api-reference/modules/_ui_enums_.userinterfacestyle

Plugin should used:
https://docs.nativescript.org/api-reference/classes/_application_.iosapplication#systemappearance
```
const app = require('tns-core-modules/application');
....
function isDarkModeEnabled() {
  return app.systemAppearance() === 'dark';
}
```

**Comment by package71** [comment]
Pull request #3
